"""
Web Report Generator - Generate security assessment reports from web search only
This module provides functionality for Claude to perform web searches and generate comprehensive reports
"""
from typing import Dict, List, Any
from datetime import datetime
import re


class WebReportGenerator:
    """Generate vendor security reports based on web search results"""

    def __init__(self, vendor_name: str, vendor_metadata: Dict[str, Any] = None):
        self.vendor_name = vendor_name
        self.vendor_metadata = vendor_metadata or {}
        self.search_results = {}

    def store_search_results(self, category: str, results: List[Dict[str, Any]]):
        """Store search results for a category"""
        self.search_results[category] = results

    def generate_comprehensive_report(self) -> str:
        """Generate comprehensive markdown report from all search results"""

        report = f"""# Vendor Security Assessment Report
# {self.vendor_name}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Assessment Type:** Web Search Analysis
**Data Source:** Publicly Available Information

---

## Executive Summary

This report provides a security assessment of **{self.vendor_name}** based on publicly available information gathered through web searches.

"""

        # Add risk level assessment
        risk_level = self._assess_overall_risk()
        risk_emoji = {'LOW': '🟢', 'MEDIUM': '🟡', 'HIGH': '🔴', 'CRITICAL': '🔴'}.get(risk_level, '⚪')

        report += f"""
### Overall Risk Assessment

{risk_emoji} **Risk Level:** {risk_level}

**Assessment Based On:**
- Company information and reputation
- Public security posture and practices
- Certifications and compliance status
- Historical security incidents
- Third-party reviews and ratings

---

## 1. Company Overview

**Vendor Name:** {self.vendor_name}
"""

        # Add metadata if provided
        if self.vendor_metadata.get('services'):
            report += f"**Services:** {self.vendor_metadata['services']}\n"
        if self.vendor_metadata.get('integrations'):
            report += f"**Integration Points:** {self.vendor_metadata['integrations']}\n"
        if self.vendor_metadata.get('data_stored'):
            report += f"**Data Handled:** {self.vendor_metadata['data_stored']}\n"

        report += "\n"

        # Company information section
        if 'company_info' in self.search_results:
            report += self._format_company_info_section()

        # Security posture section
        if 'security_info' in self.search_results:
            report += self._format_security_section()

        # Certifications section
        if 'certifications' in self.search_results:
            report += self._format_certifications_section()

        # Incidents section
        if 'incidents' in self.search_results:
            report += self._format_incidents_section()

        # Reviews section
        if 'reviews' in self.search_results:
            report += self._format_reviews_section()

        # Recommendations
        report += self._generate_recommendations()

        # Sources
        report += self._format_sources()

        report += """
---

## Disclaimer

This assessment is based solely on publicly available information gathered through web searches. It should not be considered a comprehensive security audit. For complete assessment, we recommend:

1. Request official security documentation (SOC 2, ISO 27001 reports)
2. Conduct vendor security questionnaire
3. Review actual integration and data flow documentation
4. Perform technical security assessment if required

---

*Report generated by Vendor Security Assessment Tool - Web Search Mode*
"""

        return report

    def _format_company_info_section(self) -> str:
        """Format company information section"""
        section = "\n### Company Information\n\n"

        results = self.search_results.get('company_info', [])
        if not results:
            section += "No company information found in public sources.\n\n"
            return section

        for idx, result in enumerate(results[:5], 1):
            title = result.get('title', 'Unknown')
            snippet = result.get('snippet', '')
            url = result.get('url', '#')

            section += f"**Source {idx}:** [{title}]({url})\n\n"
            section += f"{snippet}\n\n"

        return section

    def _format_security_section(self) -> str:
        """Format security posture section"""
        section = "\n---\n\n## 2. Security Posture\n\n"

        results = self.search_results.get('security_info', [])
        if not results:
            section += "⚠️ **Limited public information available** about security practices.\n\n"
            section += "**Recommendation:** Request detailed security documentation from vendor.\n\n"
            return section

        section += "### Public Security Information\n\n"

        # Extract security keywords
        security_keywords = set()
        for result in results:
            text = f"{result.get('title', '')} {result.get('snippet', '')}".lower()
            keywords = ['encryption', 'firewall', 'authentication', 'mfa', '2fa', 'access control',
                       'monitoring', 'siem', 'penetration test', 'security audit', 'vulnerability',
                       'patch management', 'incident response', 'backup', 'disaster recovery']

            for kw in keywords:
                if kw in text:
                    security_keywords.add(kw)

        if security_keywords:
            section += "**Security Controls Mentioned:**\n"
            for kw in sorted(security_keywords):
                section += f"- {kw.title()}\n"
            section += "\n"

        # List sources
        for idx, result in enumerate(results[:5], 1):
            title = result.get('title', 'Unknown')
            snippet = result.get('snippet', '')
            url = result.get('url', '#')

            section += f"**Finding {idx}:** [{title}]({url})\n\n"
            section += f"{snippet}\n\n"

        return section

    def _format_certifications_section(self) -> str:
        """Format certifications section"""
        section = "\n---\n\n## 3. Certifications & Compliance\n\n"

        results = self.search_results.get('certifications', [])
        if not results:
            section += "⚠️ **No public certification information found.**\n\n"
            section += "**Recommendation:** Request copies of SOC 2, ISO 27001, or other relevant certifications.\n\n"
            return section

        # Extract certification keywords
        cert_keywords = []
        for result in results:
            text = f"{result.get('title', '')} {result.get('snippet', '')}".lower()

            if 'soc 2' in text or 'soc2' in text:
                cert_keywords.append('SOC 2')
            if 'iso 27001' in text or 'iso27001' in text:
                cert_keywords.append('ISO 27001')
            if 'iso 27017' in text:
                cert_keywords.append('ISO 27017')
            if 'pci dss' in text or 'pci-dss' in text:
                cert_keywords.append('PCI DSS')
            if 'hipaa' in text:
                cert_keywords.append('HIPAA')
            if 'gdpr' in text:
                cert_keywords.append('GDPR Compliant')
            if 'fedramp' in text:
                cert_keywords.append('FedRAMP')

        if cert_keywords:
            section += "### Certifications Mentioned\n\n"
            for cert in sorted(set(cert_keywords)):
                section += f"✓ **{cert}**\n"
            section += "\n**Note:** Verify current status and request official certification documents.\n\n"

        section += "### Sources\n\n"
        for idx, result in enumerate(results[:5], 1):
            title = result.get('title', 'Unknown')
            snippet = result.get('snippet', '')
            url = result.get('url', '#')

            section += f"{idx}. [{title}]({url})\n"
            section += f"   {snippet[:200]}...\n\n"

        return section

    def _format_incidents_section(self) -> str:
        """Format security incidents section"""
        section = "\n---\n\n## 4. Security Incidents & Breaches\n\n"

        results = self.search_results.get('incidents', [])
        if not results:
            section += "✅ **No public security incidents found** in recent searches.\n\n"
            section += "*Note: This does not guarantee absence of incidents. Limited to publicly disclosed information.*\n\n"
            return section

        section += f"⚠️ **{len(results)} potential security incident(s) or vulnerability report(s) found:**\n\n"

        for idx, result in enumerate(results, 1):
            title = result.get('title', 'Unknown')
            snippet = result.get('snippet', '')
            url = result.get('url', '#')

            # Try to extract year
            year_match = re.search(r'\b(20\d{2})\b', f"{title} {snippet}")
            year = year_match.group(1) if year_match else 'Date unknown'

            section += f"### Incident {idx} ({year})\n\n"
            section += f"**Source:** [{title}]({url})\n\n"
            section += f"**Details:** {snippet}\n\n"
            section += f"**Action Required:** Investigate this incident and request vendor's remediation report.\n\n"

        return section

    def _format_reviews_section(self) -> str:
        """Format security reviews section"""
        section = "\n---\n\n## 5. Third-Party Reviews & Reputation\n\n"

        results = self.search_results.get('reviews', [])
        if not results:
            section += "No third-party security reviews found in public sources.\n\n"
            return section

        section += "### Public Reviews & Assessments\n\n"

        for idx, result in enumerate(results[:5], 1):
            title = result.get('title', 'Unknown')
            snippet = result.get('snippet', '')
            url = result.get('url', '#')

            section += f"**Review {idx}:** [{title}]({url})\n\n"
            section += f"{snippet}\n\n"

        return section

    def _generate_recommendations(self) -> str:
        """Generate recommendations based on findings"""
        section = "\n---\n\n## 6. Recommendations\n\n"

        recommendations = []

        # Check for certifications
        if not self.search_results.get('certifications'):
            recommendations.append({
                'priority': 'HIGH',
                'action': 'Request Security Certifications',
                'details': 'No public certification information found. Request SOC 2 Type II, ISO 27001, or equivalent certifications.'
            })

        # Check for incidents
        if self.search_results.get('incidents'):
            recommendations.append({
                'priority': 'CRITICAL',
                'action': 'Investigate Security Incidents',
                'details': f"Public records show {len(self.search_results['incidents'])} security incident(s). Request incident reports and remediation evidence."
            })

        # Check for security info
        if not self.search_results.get('security_info'):
            recommendations.append({
                'priority': 'HIGH',
                'action': 'Request Security Documentation',
                'details': 'Limited public information about security practices. Request comprehensive security documentation package.'
            })

        # Always recommend full assessment
        recommendations.append({
            'priority': 'MEDIUM',
            'action': 'Conduct Full Security Assessment',
            'details': 'Complete vendor security questionnaire and review detailed security documentation for comprehensive assessment.'
        })

        for idx, rec in enumerate(recommendations, 1):
            priority_emoji = {'CRITICAL': '🔴', 'HIGH': '🟠', 'MEDIUM': '🟡', 'LOW': '🟢'}.get(rec['priority'], '⚪')
            section += f"### {idx}. {priority_emoji} [{rec['priority']}] {rec['action']}\n\n"
            section += f"{rec['details']}\n\n"

        return section

    def _format_sources(self) -> str:
        """Format sources appendix"""
        section = "\n---\n\n## Appendix: Information Sources\n\n"

        all_sources = []
        for category, results in self.search_results.items():
            for result in results:
                url = result.get('url', '')
                title = result.get('title', 'Unknown')
                if url and url not in [s['url'] for s in all_sources]:
                    all_sources.append({'title': title, 'url': url, 'category': category})

        section += "All information in this report was gathered from the following public sources:\n\n"

        for idx, source in enumerate(all_sources[:20], 1):
            section += f"{idx}. [{source['title']}]({source['url']}) - *{source['category'].replace('_', ' ').title()}*\n"

        section += f"\n**Total Sources:** {len(all_sources)}\n\n"

        return section

    def _assess_overall_risk(self) -> str:
        """Assess overall risk level based on findings"""

        # Check for incidents
        if self.search_results.get('incidents') and len(self.search_results['incidents']) > 0:
            return 'HIGH'

        # Check for certifications
        has_certs = bool(self.search_results.get('certifications'))

        # Check for security info
        has_security_info = bool(self.search_results.get('security_info'))

        if has_certs and has_security_info:
            return 'MEDIUM'
        elif has_certs or has_security_info:
            return 'MEDIUM'
        else:
            return 'HIGH'

    def save_report(self, output_path: str) -> str:
        """Generate and save report to file"""
        report_content = self.generate_comprehensive_report()

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(report_content)

        return output_path
